services:
  - name: emotion-backend
    type: web
    env: python
    region: oregon
    branch: main
    # Force a python version compatible with your pinned packages
    pythonVersion: "3.11"
    # Build from repository; backend is inside the 'backend' folder
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && gunicorn main:app --bind 0.0.0.0:$PORT --workers 1
    autoDeploy: true
